**Installing libraries**

In [1]:
import pandas as pd

**Importing files and dropping unnecessary columns**

*Race Data*

In [2]:
#All files will be read in this cell in their raw form
race_data = pd.read_csv(r'D:\Projects\Formula 1\f1db_csv\races.csv')

In [33]:
race_data.columns

Index(['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'time', 'url',
       'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time',
       'quali_date', 'quali_time', 'sprint_date', 'sprint_time'],
      dtype='object')

In [26]:
columns = ['raceId','year','round','circuitId','name','date']

In [27]:
#race data
df_race = race_data[columns]

*Circuit Data*

In [16]:
circuit_data = pd.read_csv(r"D:\Projects\Formula 1\f1db_csv\circuits.csv")

In [20]:
circuit_data.columns

Index(['circuitId', 'circuitRef', 'name', 'location', 'country', 'lat', 'lng',
       'alt', 'url'],
      dtype='object')

In [28]:
columns = ['circuitId', 'name', 'location', 'country', 'lat', 'lng']

In [29]:
#circuit data
df_circuit = circuit_data[columns]

*Constructor Data*

In [31]:
cons_data = pd.read_csv(r"D:\Projects\Formula 1\f1db_csv\constructors.csv")

In [32]:
cons_data.columns

Index(['constructorId', 'constructorRef', 'name', 'nationality', 'url'], dtype='object')

In [35]:
columns = ['constructorId', 'name']

In [36]:
df_constructor = cons_data[columns]

*Driver Data*

In [39]:
driver_data = pd.read_csv(r"D:\Projects\Formula 1\f1db_csv\drivers.csv")

In [41]:
driver_data.columns

Index(['driverId', 'driverRef', 'number', 'code', 'forename', 'surname', 'dob',
       'nationality', 'url'],
      dtype='object')

In [43]:
columns = ['driverId', 'number', 'code', 'forename', 'surname', 'dob', 'nationality']

In [44]:
df_driver = driver_data[columns]

*Qualifying Data*

In [58]:
quali_data = pd.read_csv(r"D:\Projects\Formula 1\f1db_csv\qualifying.csv")

In [59]:
quali_data.head()

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

In [60]:
quali_data.columns

Index(['qualifyId', 'raceId', 'driverId', 'constructorId', 'number',
       'position', 'q1', 'q2', 'q3'],
      dtype='object')

In [61]:
columns = ['qualifyId', 'raceId', 'driverId', 'constructorId', 'number', 'position']

In [62]:
df_quali = quali_data[columns]

In [64]:
driver_num = df_quali['number']

In [66]:
df_quali['driver_num'] = driver_num

C:\Users\femin\AppData\Local\Temp\ipykernel_18352\623012824.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_quali['driver_num'] = driver_num

In [69]:
df_quali.drop(columns = 'number')

       qualifyId  raceId  driverId  constructorId  position  driver_num
0              1      18         1              1         1          22
1              2      18         9              2         2           4
2              3      18         5              1         3          23
3              4      18        13              6         4           2
4              5      18         2              2         5           3
...          ...     ...       ...            ...       ...         ...
10089      10147    1124       840            117        16          18
10090      10148    1124       842            214        17          10
10091      10149    1124       825            210        18          20
10092      10150    1124       858              3        19           2
10093      10151    1124       855             15        20          24

[10094 rows x 6 columns]

*Sprint Results Data*

In [70]:
sprint_data = pd.read_csv(r"D:\Projects\Formula 1\f1db_csv\sprint_results.csv")

In [71]:
sprint_data.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1

In [75]:
driver_num = sprint_data['number']

In [78]:
sprint_data['driver_num'] = driver_num

In [84]:
sprint_data = sprint_data.drop(columns = 'number')

In [87]:
sprint_data.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'grid', 'position',
       'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'fastestLapTime', 'statusId',
       'driver_num'],
      dtype='object')

In [103]:
columns = ['resultId', 'raceId', 'driverId', 'constructorId', 'grid',
       'position', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'fastestLapTime', 
       'driver_num']

In [104]:
df_sprint = sprint_data[columns]

*Results Data*

In [91]:
results_data = pd.read_csv(r"D:\Projects\Formula 1\f1db_csv\results.csv")

In [94]:
driver_num = results_data['number']

In [97]:
results_data['driver_num'] = driver_num

In [100]:
results_data = results_data.drop(columns = 'number')

In [101]:
results_data.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'grid', 'position',
       'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'driver_num'],
      dtype='object')

In [102]:
results_data.head()

,resultId,raceId,driverId,constructorId,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,driver_num
0,1,18,1,1,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,22
1,2,18,2,2,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,3
2,3,18,3,3,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,7
3,4,18,4,4,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,5
4,5,18,5,1,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,23

In [106]:
columns = ['resultId', 'raceId', 'driverId', 'constructorId', 'grid', 'position', 'points', 'laps', 'time',
       'milliseconds', 'rank', 'fastestLapTime','driver_num']

In [107]:
df_results = results_data[columns]

*Pitstop Data*

In [110]:
pitstop_data = pd.read_csv(r"D:\Projects\Formula 1\f1db_csv\pit_stops.csv")

In [112]:
pitstop_data.head()

   raceId  driverId  stop  lap      time duration  milliseconds
0     841       153     1    1  17:05:23   26.898         26898
1     841        30     1    1  17:05:52   25.021         25021
2     841        17     1   11  17:20:48   23.426         23426
3     841         4     1   12  17:22:34   23.251         23251
4     841        13     1   13  17:24:10   23.842         23842

In [113]:
pitstop_data.columns

Index(['raceId', 'driverId', 'stop', 'lap', 'time', 'duration',
       'milliseconds'],
      dtype='object')

In [115]:
columns = ['raceId', 'driverId', 'lap', 'duration',
       'milliseconds']

In [116]:
df_pitstop = pitstop_data[columns]

*Driver Standings Data*

In [118]:
driver_stand_data = pd.read_csv(r"D:\Projects\Formula 1\f1db_csv\driver_standings.csv")

In [119]:
driver_stand_data.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [120]:
driver_stand_data = driver_stand_data.drop(columns = 'positionText')

In [123]:
df_driver_stand = driver_stand_data

*Constructor Standings Data*

In [125]:
cons_stand_data = pd.read_csv(r"D:\Projects\Formula 1\f1db_csv\constructor_standings.csv")

In [126]:
cons_stand_data = cons_stand_data.drop(columns = 'positionText')

In [127]:
df_cons_stand = cons_stand_data